name: entangle_line_threefork_master_obs_follow
# name: pick_waste_hist2s

image_shape: [3, 480, 640]
low_dim_obs_horizon: 1
img_obs_horizon: 1
action_horizon: 20
action_history_length: 0
image_history_length: 0
is_binocular: False
is_factory: False # 只x+0.15,z+0.2
use_quaternion: False # 采用四元数来表示旋转
relative_action: False # 采用相对位姿
add_noise: False
filter_angle_outliers: False # 过滤角度异常值会报错
minmax_range_robot: arx_master_obs_follow
use_joint_cur: False

dataset_path:
- path: /x2robot/zhengwei/factory10021/20250306-day-entangled-line-three-fork
- path: /x2robot/zhengwei/factory10022/20250306-day-entangled-line-three-fork-disturb
- path: /x2robot/zhengwei/factory10020/20250306-day-entangled-line-three-fork-disturb
- path: /x2robot/zhengwei/factory10023/20250306-night-entangled-line-three-fork-disturb
- path: /x2robot/zhengwei/factory10020/20250306-night-entangled-line-three-fork-disturb
- path: /x2robot/zhengwei/factory10021/20250307-day-entangled-line-three-fork-disturb
- path: /x2robot/zhengwei/factory10022/20250307-day-entangled-line-three-fork-disturb
- path: /x2robot/zhengwei/factory10021/20250307-night-entangled-line-three-fork-disturb
- path: /x2robot/zhengwei/factory10022/20250307-night-entangled-line-three-fork-disturb
- path: /x2robot/zhengwei/factory10021/20250308-day-entangled-line-three-fork-disturb
- path: /x2robot/zhengwei/factory10021/20250308-night-entangled-line-three-fork-disturb
- path: /x2robot/zhengwei/factory10020/20250308-night-entangled-line-three-fork-disturb
- path: /x2robot/zhengwei/factory10021/20250309-day-entangled-line-three-fork-disturb
- path: /x2robot/zhengwei/factory10020/20250309-night-entangled-line-three-fork-disturb
- path: /x2robot/zhengwei/factory10026/20250309-night-entangled-line-three-fork-disturb
- path: /x2robot/zhengwei/factory10021/20250310-night-entangled-fork-three-fork-disturb
- path: /x2robot/zhengwei/factory10020/20250310-night-entangled-line-three-fork-disturb
- path: /x2robot/zhengwei/factory10021/20250310-night-entangled-line-three-fork-disturb
- path: /x2robot/zhengwei/factory10020/20250310-day-entangled-line-three-fork-disturb
- path: /x2robot/zhengwei/factory10020/20250311-night-entangled-line-three-fork-disturb
- path: /x2robot/zhengwei/factory10026/20250311-night-entangled-line-three-fork-disturb
- path: /x2robot/zhengwei/factory10021/20250311-night-entangled-line-three-fork-disturb
- path: /x2robot/zhengwei/factory10021/20250311-day-entangled-line-three-fork-disturb
- path: /x2robot/zhengwei/factory10019/20250311-day-entangled-line-three-fork-disturb
- path: /x2robot/zhengwei/factory10021/20250311-night-entangled-line-three-fork-disturb
- path: /x2robot/zhengwei/factory10026/20250311-night-entangled-line-three-fork-disturb
- path: /x2robot/zhengwei/factory10020/20250311-night-entangled-line-three-fork-disturb
- path: /x2robot/zhengwei/factory10021/20250312-day-entangled-line-three-fork-disturb
- path: /x2robot/zhengwei/factory10023/20250312-day-entangled-line-three-fork-disturb
- path: /x2robot/zhengwei/factory10026/20250312-night-entangled-line-three-fork-disturb
- path: /x2robot/zhengwei/factory10020/20250228-day-entangled-line-three-fork-new-setting
- path: /x2robot/zhengwei/factory10021/20250313-day-entangled-line-three-fork-disturb
- path: /x2robot/zhengwei/factory10023/20250313-day-entangled-line-three-fork-disturb
- path: /x2robot/zhengwei/factory10026/20250313-night-entangled-line-three-fork-disturb
- path: /x2robot/zhengwei/factory10023/20250313-night-entangled-line-three-fork-disturb
- path: /x2robot/zhengwei/factory10023/20250314-day-entangled-line-three-fork-disturb
- path: /x2robot/zhengwei/factory10023/20250315-day-entangled-line-three-fork-disturb
- path: /x2robot/zhengwei/factory10026/20250314-night-entangled-line-three-fork-disturb
- path: /x2robot/zhengwei/factory10021/20250315-night-entangled-line-three-fork-disturb
- path: /x2robot/zhengwei/factory10027/20250316-day-entangled-line-three-fork-disturb
- path: /x2robot/zhengwei/factory10021/20250316-night-entangled-line-three-fork-disturb
- path: /x2robot/zhengwei/factory10027/20250316-night-entangled-line-three-fork-disturb
- path: /x2robot/zhengwei/factory10025/20250317-day-entangled-line-three-fork-disturb
- path: /x2robot/zhengwei/factory10026/20250317-night-entangled-line-three-fork-disturb


shape_meta: &shape_meta
  obs:
    face_view:
      shape: ${task.image_shape}
      horizon: ${task.img_obs_horizon}
      type: rgb
    left_wrist_view:
      shape: ${task.image_shape}
      horizon: ${task.img_obs_horizon}
      type: rgb
    right_wrist_view:
      shape: ${task.image_shape}
      horizon: ${task.img_obs_horizon}
      type: rgb
    agent_pos:
      shape: [14] # 14 + 14
      horizon: ${eval:'${task.low_dim_obs_horizon} + ${task.action_history_length}'}
      type: low_dim
  action:
    shape: [14]
    horizon: ${task.action_horizon}
    type: low_dim

dataset:
  dataset_paths: ${task.dataset_path}
  # seed: 42
  is_bi_mode: True
  repeat_num: 1
  train_val_split: 0.95
  # sample_ratio: [1.0, 1.0]
  save_meta_data: True
  force_overwrite: False