name: forewarn
# name: pick_waste_hist2s

image_shape: [3, 480, 640]
low_dim_obs_horizon: 1
img_obs_horizon: 1
action_horizon: 20
action_history_length: 0
image_history_length: 0
is_binocular: False
is_factory: False # 只x+0.15,z+0.2
use_quaternion: False # 采用四元数来表示旋转
relative_action: False # 采用相对位姿
add_noise: False
filter_angle_outliers: False # 过滤角度异常值会报错
minmax_range_robot: arx
use_gripper_cur: True # 使用力控 


dataset_path:
- path: /x2robot/zhengwei/10006/20250307-day-pick_up-cup-test
# - path: /x2robot/zhengwei/rl_dataset/10006/20250312-night-pick_up-cup-test
- path: /x2robot/zhengwei/10006/20250312-night-pick_up-cup-test-positive

shape_meta: &shape_meta
  obs:
    face_view:
      shape: ${task.image_shape}
      horizon: ${task.img_obs_horizon}
      type: rgb
    left_wrist_view:
      shape: ${task.image_shape}
      horizon: ${task.img_obs_horizon}
      type: rgb
    right_wrist_view:
      shape: ${task.image_shape}
      horizon: ${task.img_obs_horizon}
      type: rgb
    agent_pos:
      shape: [16]
      horizon: ${eval:'${task.low_dim_obs_horizon} + ${task.action_history_length}'}
      type: low_dim
  action:
    shape: [14]
    horizon: ${task.action_horizon}
    type: low_dim

dataset:
  dataset_paths: ${task.dataset_path}
  # seed: 42
  is_bi_mode: True
  repeat_num: 1
  train_val_split: 0.9
  # sample_ratio: [1.0, 1.0]
  save_meta_data: True
  force_overwrite: False