name: hand_pick_pos
# name: hand_pick_joint

image_shape: [3, 480, 640]
low_dim_obs_horizon: 1
img_obs_horizon: 1
action_horizon: 40
action_history_length: 0
image_history_length: 0
filter_angle_outliers: False # 过滤角度异常值会报错
trim_stationary: True # 是否去除静止动作
task_config_path: /x2robot/ganruyi/code/diffusion_policy/diffusion_policy/config/task/hand_pick.yaml

# 强制配置两个action keys
predict_action_keys:
  - follow_left_ee_cartesian_pos_jaka
  - follow_left_ee_rotation_jaka
  - follow_left_hand_joint_pos
  - follow_right_ee_cartesian_pos_jaka
  - follow_right_ee_rotation_jaka
  - follow_right_hand_joint_pos

# obs_action_keys必须配置，不能缺失
obs_action_keys:
  - follow_left_ee_cartesian_pos_jaka
  - follow_left_ee_rotation_jaka
  - follow_left_hand_joint_pos
  - follow_right_ee_cartesian_pos_jaka
  - follow_right_ee_rotation_jaka
  - follow_right_hand_joint_pos
  # 如果需要额外的观测数据（比如力控），可以在这里加：
  # - follow_left_gripper_cur
  # - follow_right_gripper_cur

dataset_path:
  - path: /x2robot/zhengwei/10078/20250521-day-pick_up-tissue
  - path: /x2robot/zhengwei/10078/20250520-day-pick_up-tissue

shape_meta: &shape_meta
  obs:
    face_view:
      shape: ${task.image_shape}
      horizon: ${task.img_obs_horizon}
      type: rgb
      camera_name: faceImg
    left_wrist_view:
      shape: ${task.image_shape}
      horizon: ${task.img_obs_horizon}
      type: rgb
      camera_name: leftImg
    right_wrist_view:
      shape: ${task.image_shape}
      horizon: ${task.img_obs_horizon}
      type: rgb
      camera_name: rightImg
    agent_pos:
      shape: [50] # arm 12, hand 38 
      horizon: ${eval:'${task.low_dim_obs_horizon} + ${task.action_history_length}'}
      type: low_dim
  action:
    shape: [50]
    horizon: ${task.action_horizon}
    type: low_dim

dataset:
  dataset_paths: ${task.dataset_path}
  # seed: 42
  repeat_num: 1
  train_val_split: 0.98
  cache_dir: /x2robot/ganruyi/.cache/dataset_cache # 实验时采用自己的缓存目录，最终会合并到/x2robot/Data/.cache/dataset_cache
  instruction: 'pick up the tissue into the box'