name: instruct_put_waypoint
# name: pick_waste_hist2s

image_shape: [3, 480, 640]
low_dim_obs_horizon: 1
img_obs_horizon: 1
action_horizon: 40
action_history_length: 0
image_history_length: 0
is_binocular: False
is_factory: False # 只x+0.15,z+0.2
use_quaternion: False # 采用四元数来表示旋转
relative_action: False # 采用相对位姿
add_noise: False
filter_angle_outliers: False # 过滤角度异常值会报错
minmax_range_robot: arx
use_gripper_cur: True # 使用力控 
task_config_path: /x2robot/caichuang/extra_codes/dp_starrick/integrated_0613/diffusion_policy/diffusion_policy/config/task/instruct_put_waypoint.yaml

predict_action_keys:
  - follow_left_ee_cartesian_pos
  - follow_left_ee_rotation
  - follow_left_gripper
  - follow_right_ee_cartesian_pos
  - follow_right_ee_rotation
  - follow_right_gripper

# obs_action_keys必须配置，不能缺失
obs_action_keys:
  - follow_left_ee_cartesian_pos
  - follow_left_ee_rotation
  - follow_left_gripper
  - follow_right_ee_cartesian_pos
  - follow_right_ee_rotation
  - follow_right_gripper
  # 如果需要额外的观测数据（比如力控），可以在这里加：
  - follow_left_gripper_cur
  - follow_right_gripper_cur

dataset_path:
# - path: /x2robot/zhengwei/10055/20250514-day-instruct-put
# - path: /x2robot/zhengwei/10064/20250514-day-instruct-put
# - path: /x2robot/zhengwei/10055/20250515-day-instruct-put

# - path: /x2robot/zhengwei/10055/20250516-day-instruct-put
# - path: /x2robot/zhengwei/10053/20250519-day-instruct-put
# - path: /x2robot/zhengwei/10055/20250519-day-instruct-put-1
# - path: /x2robot/zhengwei/10063/20250522-day-instruct-put-1
# - path: /x2robot/zhengwei/factory10022/20250527-day-instruct-put-1
# - path: /x2robot/zhengwei/factory10018/20250527-day-instruct-put
# - path: /x2robot/zhengwei/factory10023/20250527-day-instruct-put-1
# - path: /x2robot/zhengwei/factory10023/20250528-day-instruct-put
# - path: /x2robot/zhengwei/factory10018/20250528-day-instruct-put

- path: /x2robot/zhengwei/factory10023/20250527-day-instruct-put-1
# - path: /x2robot/zhengwei/10055/20250516-day-instruct-put
# - path: /x2robot/zhengwei/factory10023/20250528-day-instruct-put
# - path: /x2robot/zhengwei/10055/20250519-day-instruct-put-1
# - path: /x2robot/zhengwei/10063/20250522-day-instruct-put-1
# - path: /x2robot/zhengwei/factory10018/20250528-day-instruct-put
# - path: /x2robot/zhengwei/factory10022/20250527-day-instruct-put-1
# - path: /x2robot/zhengwei/10053/20250519-day-instruct-put
# - path: /x2robot/zhengwei/factory10018/20250527-day-instruct-put

shape_meta: &shape_meta
  obs:
    face_view:
      shape: ${task.image_shape}
      horizon: ${task.img_obs_horizon}
      type: rgb
      camera_name: faceImg
    left_wrist_view:
      shape: ${task.image_shape}
      horizon: ${task.img_obs_horizon}
      type: rgb
      camera_name: leftImg
    right_wrist_view:
      shape: ${task.image_shape}
      horizon: ${task.img_obs_horizon}
      type: rgb
      camera_name: rightImg
    agent_pos:
      shape: [16]
      horizon: ${eval:'${task.low_dim_obs_horizon} + ${task.action_history_length}'}
      type: low_dim
  action:
    shape: [14]
    horizon: ${task.action_horizon}
    type: low_dim

dataset:
  dataset_paths: ${task.dataset_path}
  seed: 42
  repeat_num: 1
  train_val_split: 0.95
  # sample_ratio: [1.0, 1.0]
  save_meta_data: True
  force_overwrite: True
  root_dir: /x2robot/caichuang/cache

visual_instruct:
  _target_: diffusion_policy.model.visual_instructors.instruct_put_waypoint.InstructPutWaypoint
  file: /x2robot/share/caichuang/instruct_files/instruct_put_waypoint_img_dict.json
  custom_defined_invalid_samples: /x2robot/share/caichuang/instruct_files/instruct_put_invalid_samples.json