defaults:
  - _self_
  - task: fold_towel

name: pi0
# name: resnet18
_target_: diffusion_policy.workspace.train_pi0.TrainPI0Workspace

task_name: ${task.name}
shape_meta: ${task.shape_meta}
exp_name: "default"

use_fsdp: True 
clip_gradnorm: 1.0
policy: /x2robot/ganruyi/models/lerobot/pi0
num_train_timesteps: 10 # pi0 默认10，改成20试试
# policy:
  # _target_: diffusion_policy.model.pi0.modeling_pi0_v2.PI0Policy

train_dataloader:
  batch_size: 8 # 4gpu for gbs=256

val_dataloader:
  batch_size: 8

optimizer:
  _target_: torch.optim.AdamW
  # lr: 5e-5
  # lr: 2.0e-4
  # betas: [0.95, 0.999]
  # eps: 1.0e-8
  # weight_decay: 1.0e-6

  lr: 2.5e-5
  betas: [0.9, 0.95]
  eps: 1.0e-8
  weight_decay: 1.0e-10


training:
  device: "cuda"
  seed: 42
  debug: False
  # debug: True
  lr_scheduler: cosine
  lr_warmup_steps: 1000
  num_epochs: 300
  gradient_accumulate_every: 1
  # EMA destroys performance when used with BatchNorm
  # replace BatchNorm with GroupNorm.
  use_ema: False
  freeze_encoder: False
  freeze_lm_encoder: False
  # training loop control
  # in epochs
  rollout_every: 1
  checkpoint_every: 5
  val_every: 5
  sample_every: 5
  # steps per epoch
  max_train_steps: null
  max_val_steps: null
  # attention implementation
  # attention_implementation: flex
  # misc
  tqdm_interval_sec: 1.0
  resume: False
  # resume: True
  # resume_ckpt_path: '/x2robot/ganruyi/workspace/diffusion_policy/2025.03.13/19.16.45_resnet50_pretrained_pick_cup_car_p20_cur/checkpoints/epoch=0195-train_loss=0.000.ckpt'  

logging:
  # project: diffusion_policy_debug
  project: fold_towel_pi0
  resume: False
  mode: online
  name: ${now:%Y.%m.%d-%H.%M.%S}_${name}_${task_name}
  tags: ["${name}", "${task_name}", "${exp_name}"]
  id: null
  group: null

checkpoint:
  topk:
    monitor_key: train_loss
    mode: min
    k: 40
    format_str: 'epoch={epoch:04d}-train_loss={train_loss:.3f}.ckpt'
  save_last_ckpt: True
  save_last_snapshot: False

multi_run:
  run_dir: /x2robot/ganruyi/workspace/diffusion_policy/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
  wandb_name_base: ${name}_${task_name}_${now:%Y.%m.%d-%H.%M.%S}

hydra:
  job:
    override_dirname: ${name}
  run:
    dir: ${multi_run.run_dir} 
  # sweep:
  #   dir: /x2robot/ganruyi/workspace/diffusion_policy/${now:%H.%M.%S}_${name}_${task_name}
  #   subdir: ${hydra.job.num}
